#!/usr/bin/env python
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
#    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#    Find the sum of all the even-valued terms in the sequence which do not
#    exceed four million.

def fibo(n):
    if n == 1:
        return 1
    elif n == 2:
        return 2
    else:
        for i in range(n):
            return fibo(n-2) + fibo(n-1)

c = 1
sum = 0
while 1:
    c = c + 1
    value = fibo(c)
    condition = sum + value
    if not value % 2:
        if value > 4000000:
            break 
        else:
            sum = sum + value

print sum 

